menu:
  #Archives: /archives
  分类: /tags/
  友链: /friendlink
  关于我: /aboutme
#rss: /atom.xml
description: 
social:
  weibo: http://weibo.com/sud0
  github: https://github.com/sud0why
  qq: http://wpa.qq.com/msgrd?v=3&uin=849853532&site=qq&menu=yes
  mail: sud0.why@gmail.com
  #wechat: 
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus: 

page_comment: true
logo: http://sudablog-10068329.file.myqcloud.com/logo.jpg
background:
  cover: http://sudablog-10068329.file.myqcloud.com/background-cover.jpg
  color: cover-slate

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: sudalover1


#cnzz_tongji: 1260564302
#google_analytics: UA-78918255-1
baidu_tongji: a37f7355ddd976b07030cbcaf56f0af5
favicon: http://sudablog-10068329.file.myqcloud.com/logo.jpg

